const PrivacyPolicy = () => {
  return (
    <div className="bg-cinematic-black min-h-screen text-white">
      <div className="container mx-auto px-6 py-16 max-w-5xl">
        <h1 className="text-4xl font-bold text-cinematic-gold mb-2">
          Privacy Policy for Dhaari
        </h1>

        <p className="text-sm text-cinematic-textMuted mb-10">
          Last updated: January 29, 2026
        </p>

        <div className="space-y-8 text-cinematic-textBody leading-relaxed">

          <p>
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>

          <p>
            We use Your Personal Data to provide and improve the Service. By using
            the Service, You agree to the collection and use of information in
            accordance with this Privacy Policy.
          </p>

          {/* Interpretation */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Interpretation and Definitions
            </h2>

            <h3 className="text-lg font-semibold mb-1">Interpretation</h3>
            <p>
              The words whose initial letters are capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
          </section>

          {/* Definitions */}
          <section>
            <h3 className="text-lg font-semibold mb-3">Definitions</h3>

            <ul className="list-disc list-inside space-y-3">
              <li><b>Account</b> means a unique account created for You to access our Service.</li>
              <li><b>Affiliate</b> means an entity that controls, is controlled by, or is under common control with a party.</li>
              <li>
                <b>Company</b> refers to SRI SUMANOHARA PRODUCTIONS PRIVATE LIMITED,
                Flat No.901, Block-A, Muppa Akshaja Crown, Narsingi Village,
                Gandipet Mandal, Hyderabad, Telangana, India – 500089.
              </li>
              <li><b>Cookies</b> are small files placed on Your device.</li>
              <li><b>Country</b> refers to Telangana, India.</li>
              <li><b>Device</b> means any device that can access the Service.</li>
              <li><b>Personal Data</b> is any information relating to an identifiable individual.We use "Personal Data" and "Personal Information" interchangeably unless a law uses a
specific term.
</li>
              <li><b>Service</b> refers to the Website.</li>
              <li><b>Service Provider</b> means any person who processes data on behalf of the Company.It refers to third-party companies or individuals employed by the
Company to facilitate the Service, to provide the Service on behalf of the Company,
to perform services related to the Service or to assist the Company in analyzing how
the Service is used.</li>
              <li><b>Usage Data</b> refers to data collected automatically,either generated by the use of the
Service or from the Service infrastructure itself (for example, the duration of a page
visit).
</li>
              <li><b>Website</b> refers to Dhaari, accessible from https://www.dhaari.org/.</li>
              <li><b>You</b> means the individual or legal entity using the Service,or the company, or other
legal entity on behalf of which such individual is accessing or using the Service, as
applicable.
</li>
            </ul>
          </section>

          {/* Data Collection */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Collecting and Using Your Personal Data
            </h2>

            <h3 className="text-lg font-semibold mb-1">Personal Data</h3>
            
            <ul className="list-disc list-inside space-y-1">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
            </ul>

            <h3 className="text-lg font-semibold mt-4 mb-1">Usage Data</h3>
            <p>
              Usage Data is collected automatically when using the Service.
Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP
address), browser type, browser version, the pages of our Service that You visit, the time
and date of Your visit, the time spent on those pages, unique device identifiers and other
diagnostic data.
When You access the Service by or through a mobile device, We may collect certain
information automatically, including, but not limited to, the type of mobile device You use,
Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating
system, the type of mobile Internet browser You use, unique device identifiers and other
diagnostic data.
We may also collect information that Your browser sends whenever You visit Our Service or
when You access the Service by or through a mobile device.

              
            </p>
          </section>

          {/* Cookies */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Tracking Technologies and Cookies
            </h2>

            <ul className="list-disc list-inside space-y-2">
              <li><b>Essential Cookies</b> – required for service functionality</li>
              <li><b>Acceptance Cookies</b> – store cookie consent</li>
              <li><b>Functionality Cookies</b> – remember user preferences</li>
            </ul>
          </section>

          {/* Use of Data */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Use of Your Personal Data
            </h2>

            <ul className="list-disc list-inside space-y-2">
              <li>To provide and maintain our Service</li>
              <li>To manage Your Account</li>
              <li>To contact You</li>
              <li>For contractual and business purposes</li>
              <li>For analytics and service improvement</li>
            </ul>
          </section>

          {/* Payments */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Payments and Transaction Data
            </h2>
            <p>
              We comply with RBI regulations and DPDP Act, 2023. We do not store
              card data. Payments are processed via PCI-DSS certified partners
              and data is stored within India.
            </p>
          </section>

          {/* Retention */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Retention of Your Personal Data
            </h2>
            <p>
              Personal Data is retained only as long as necessary to comply with
              legal obligations, resolve disputes, and enforce agreements.
            </p>
          </section>

          {/* Security */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Security of Your Personal Data
            </h2>
            <p>
              We use commercially reasonable security measures but cannot
              guarantee absolute security.
            </p>
          </section>

          {/* Children */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Children's Privacy
            </h2>
            <p>
              Our Service does not address anyone under the age of 16.
            </p>
          </section>

          {/* External Links */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Links to Other Websites
            </h2>
            <p>
              We are not responsible for third-party website content or policies.
            </p>
          </section>

          {/* Updates */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Changes to this Privacy Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. Changes are
              effective when posted.
            </p>
          </section>

          {/* Contact */}
          <section>
            <h2 className="text-2xl font-semibold text-cinematic-gold mb-2">
              Contact
            </h2>
            <p>
              Email us at <span className="text-cinematic-gold">info@dhaari.org</span>
            </p>
          </section>

        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
